### ISSUE TITLE
授權請求

### ISSUE THREAD

**Issue by sakarie9** [zubonko/DOL_BJ_hair_extend#3]
您好，我在維護 [Lyra](https://github.com/sakarie9/DoL-Lyra) 整合包，也就是前 DOL-CHS-MODS。非常喜歡您的擴充包，請問我可以將您的擴充包加入到整合包內嗎

**Comment by zubonko** [comment]
> 您好，我在維護 [Lyra](https://github.com/sakarie9/DoL-Lyra) 整合包，也就是前 DOL-CHS-MODS。非常喜歡您的擴充包，請問我可以將您的擴充包加入到整合包內嗎

你好，沒問題的請自由使用！

**Comment by sakarie9** [comment]
謝謝佬！會在readme標明來源的！
